// flow-typed signature: 9ae3c476ae4d01ff404d602812fa4fcc
// flow-typed version: <<STUB>>/cspell_v4.1.2/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cspell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cspell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cspell/bin' {
  declare module.exports: any;
}

declare module 'cspell/dist/app' {
  declare module.exports: any;
}

declare module 'cspell/dist/application' {
  declare module.exports: any;
}

declare module 'cspell/dist' {
  declare module.exports: any;
}

declare module 'cspell/dist/util/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cspell/bin.js' {
  declare module.exports: $Exports<'cspell/bin'>;
}
declare module 'cspell/dist/app.js' {
  declare module.exports: $Exports<'cspell/dist/app'>;
}
declare module 'cspell/dist/application.js' {
  declare module.exports: $Exports<'cspell/dist/application'>;
}
declare module 'cspell/dist/index' {
  declare module.exports: $Exports<'cspell/dist'>;
}
declare module 'cspell/dist/index.js' {
  declare module.exports: $Exports<'cspell/dist'>;
}
declare module 'cspell/dist/util/util.js' {
  declare module.exports: $Exports<'cspell/dist/util/util'>;
}
