// flow-typed signature: 232cad9d7a8decabf870a27cef2fbee1
// flow-typed version: <<STUB>>/eslint-plugin-internal-rules_vfile:./resources/eslint-internal-rules/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-internal-rules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-internal-rules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-internal-rules/no-dir-import' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-internal-rules/index' {
  declare module.exports: $Exports<'eslint-plugin-internal-rules'>;
}
declare module 'eslint-plugin-internal-rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-internal-rules'>;
}
declare module 'eslint-plugin-internal-rules/no-dir-import.js' {
  declare module.exports: $Exports<
    'eslint-plugin-internal-rules/no-dir-import',
  >;
}
