// flow-typed signature: 77e7cb709fd13b2721d4766f58d6131e
// flow-typed version: <<STUB>>/eslint-plugin-istanbul_v0.1.2/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-istanbul/rules/no-ignore-file' {
  declare module.exports: any;
}

declare module 'eslint-plugin-istanbul/rules/prefer-ignore-reason' {
  declare module.exports: any;
}

declare module 'eslint-plugin-istanbul/utils/get-documentation-url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-istanbul/index' {
  declare module.exports: $Exports<'eslint-plugin-istanbul'>;
}
declare module 'eslint-plugin-istanbul/index.js' {
  declare module.exports: $Exports<'eslint-plugin-istanbul'>;
}
declare module 'eslint-plugin-istanbul/rules/no-ignore-file.js' {
  declare module.exports: $Exports<
    'eslint-plugin-istanbul/rules/no-ignore-file',
  >;
}
declare module 'eslint-plugin-istanbul/rules/prefer-ignore-reason.js' {
  declare module.exports: $Exports<
    'eslint-plugin-istanbul/rules/prefer-ignore-reason',
  >;
}
declare module 'eslint-plugin-istanbul/utils/get-documentation-url.js' {
  declare module.exports: $Exports<
    'eslint-plugin-istanbul/utils/get-documentation-url',
  >;
}
