// flow-typed signature: b57f89a43eca9bb95ee0fd58666cbbed
// flow-typed version: <<STUB>>/own-namespace_v^0.4.3/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'own-namespace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'own-namespace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'own-namespace/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'own-namespace/index' {
  declare module.exports: $Exports<'own-namespace'>;
}
declare module 'own-namespace/index.js' {
  declare module.exports: $Exports<'own-namespace'>;
}
declare module 'own-namespace/test.js' {
  declare module.exports: $Exports<'own-namespace/test'>;
}
