// flow-typed signature: 949fde9e3ff87da0bfa799955b65ff97
// flow-typed version: <<STUB>>/solid-namespace_v^0.5.0/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'solid-namespace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'solid-namespace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'solid-namespace/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'solid-namespace/index' {
  declare module.exports: $Exports<'solid-namespace'>;
}
declare module 'solid-namespace/index.js' {
  declare module.exports: $Exports<'solid-namespace'>;
}
declare module 'solid-namespace/test.js' {
  declare module.exports: $Exports<'solid-namespace/test'>;
}
